/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityLog: typeof import('./src/components/logs/ActivityLog.vue')['default']
    BottomDock: typeof import('./src/components/shell/BottomDock.vue')['default']
    FileList: typeof import('./src/components/files/FileList.vue')['default']
    FilePane: typeof import('./src/components/files/FilePane.vue')['default']
    FilePreviewDialog: typeof import('./src/components/files/FilePreviewDialog.vue')['default']
    FileRow: typeof import('./src/components/files/FileRow.vue')['default']
    FileToolbar: typeof import('./src/components/files/FileToolbar.vue')['default']
    LogTailViewer: typeof import('./src/components/logs/LogTailViewer.vue')['default']
    PathBreadcrumb: typeof import('./src/components/files/PathBreadcrumb.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionManagerView: typeof import('./src/components/sessions/SessionManagerView.vue')['default']
    SiteFormDialog: typeof import('./src/components/sessions/SiteFormDialog.vue')['default']
    SiteTabBar: typeof import('./src/components/shell/SiteTabBar.vue')['default']
    TerminalView: typeof import('./src/components/terminal/TerminalView.vue')['default']
    TitleBar: typeof import('./src/components/shell/TitleBar.vue')['default']
    TransferItem: typeof import('./src/components/transfers/TransferItem.vue')['default']
    TransferQueue: typeof import('./src/components/transfers/TransferQueue.vue')['default']
    UAlert: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UFormField: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UProgress: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    URadioGroup: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
  }
}
