name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  ci:
    # Prevent infinite recursion from commits made by this workflow
    if: github.actor != 'github-actions[bot]'

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: ./.github/actions/setup-node-deps

      - run: npm run typecheck

      - run: npm test

      - run: cargo check --manifest-path src-tauri/Cargo.toml
